Throw NotFoundHttpException when debug is disabled
Propaganistas/Laravel-FakeId pull request #13
Opened 2017-04-10 12:57 UTC by yemenifree

Throw NotFoundHttpException when debug is disabled and pass string in
URL

for example `http://site.com/user/1844379023` work find but
`http://site.com/user/test` throw InvalidArgumentException

2017-04-10 15:57 UTC, Propaganistas requested changes
Thanks. Good addition. Please process my feedback. Could you also add tests?

2017-04-10 15:57 UTC, Propaganistas commented on src/FakeIdServiceProvider.php
> +                        throw config('app.debug') ? new  \InvalidArgumentException($e->getMessage()) : new NotFoundHttpException;
No need to reconstruct an InvalidArgumentException. Just rethrow `$e`:

```php
throw config('app.debug') ? $e : new NotFoundHttpException;
```

2017-04-10 17:55 UTC, salkhwlani reviewed
you right, check now

2017-04-11 20:19 UTC, Propaganistas approved these changes

2017-04-11 20:22 UTC, Propaganistas commented
The tests are failing. Please fix and also revert the tests file structure & Route facade use.

2017-04-12 15:49 UTC, merged

2017-04-12 16:21 UTC, Propaganistas commented
Thanks. A new release has been tagged: `2.0.6`